server:
  port: 9090

spring:
  servlet:
    multipart:
      max-file-size: 20MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wen?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root

